name: codex-ci

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  codex-ci:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      NODE_OPTIONS: --max-old-space-size=4096
    defaults:
      run:
        working-directory: admin-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        continue-on-error: true
        run: |
          npm run test:ci && echo "TESTS_FAILED=0" >> $GITHUB_ENV || echo "TESTS_FAILED=1" >> $GITHUB_ENV
      - name: Build
        run: npm run build
      - name: Run e2e tests
        continue-on-error: true
        run: |
          npm run ci:e2e && echo "E2E_FAILED=0" >> $GITHUB_ENV || echo "E2E_FAILED=1" >> $GITHUB_ENV
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            admin-app/reports
            admin-app/playwright-report
      - name: Codex fix
        if: env.TESTS_FAILED == '1' || env.E2E_FAILED == '1'
        env:
          JUNIT_PATH: reports/junit/junit.xml
          COVERAGE_PATH: reports/coverage/coverage-summary.json
        run: node tools/codex-fix.mjs
